#!/bin/bash

set -ex

PROXY_USER="${PROXY_USER:-rhoai}"
PROXY_PASSWORD="${PROXY_PASSWORD:-12345678}"
PULL_SECRET="$(cat "${PULL_SECRET}" | jq -c)"
CLUSTER_NAME="${CLUSTER_NAME:-rhoai}"
BASE_DOMAIN="${BASE_DOMAIN:-shiftstack.test}"
SSH_PUB_KEY="$(cat "${SSH_PUB_KEY}")"
MASTER_COUNT="${MASTER_COUNT:-3}"
WORKER_COUNT="${WORKER_COUNT:-1}"
OPENSHIFT_NETWORKTYPE="${OPENSHIFT_NETWORKTYPE:-OVNKubernetes}"
OPENSTACK_FLAVOR="${OPENSTACK_FLAVOR:-master}"
OPENSTACK_WORKER_FLAVOR="${OPENSTACK_WORKER_FLAVOR:-worker}"
OPENSTACK_EXTERNAL_NETWORK="${OPENSTACK_EXTERNAL_NETWORK:-public}"

export OS_CLOUD=default

ARTIFACT_DIR=../clusters/${CLUSTER_NAME}

FLOATINGIP_API=$(openstack floating ip create "$OPENSTACK_EXTERNAL_NETWORK" --description "${CLUSTER_NAME}-api" --format value --column floating_ip_address)
FLOATINGIP_INGRESS=$(openstack floating ip create "$OPENSTACK_EXTERNAL_NETWORK" --description "${CLUSTER_NAME}-ingress" --format value --column floating_ip_address)
ALLOW_SSH=$(openstack security group show allow-ssh -f json | jq -r .id)

if [ ! -f "${ARTIFACT_DIR}"/install-config.yaml ]; then
    cat > "${ARTIFACT_DIR}"/install-config.yaml << EOF
apiVersion: v1
baseDomain: ${BASE_DOMAIN}
compute:
- name: worker
  platform:
    openstack:
      zones: []
      additionalNetworkIDs: []
      type: ${OPENSTACK_WORKER_FLAVOR}
  replicas: ${WORKER_COUNT}
controlPlane:
  name: master
  platform:
    openstack:
      zones: []
      type: ${OPENSTACK_FLAVOR}
      additionalSecurityGroupIDs: ["${ALLOW_SSH}"]
  replicas: ${MASTER_COUNT}
metadata:
  name: ${CLUSTER_NAME}
networking:
  clusterNetworks:
  - cidr:    10.128.0.0/14
    hostSubnetLength: 9
  serviceCIDR: 172.30.0.0/16
  machineCIDR: 10.196.0.0/16
  type: ${OPENSHIFT_NETWORKTYPE}
platform:
  openstack:
    cloud:            ${OS_CLOUD}
    externalNetwork:  ${OPENSTACK_EXTERNAL_NETWORK}
    region:         "regionOne"
    apiFloatingIP:  ${FLOATINGIP_API}
    ingressFloatingIP:  ${FLOATINGIP_INGRESS}
    externalDNS:    ["192.168.122.1"]
proxy:
  httpProxy: http://${PROXY_USER}:${PROXY_PASSWORD}@192.168.130.1:3128
  httpsProxy: http://${PROXY_USER}:${PROXY_PASSWORD}@192.168.130.1:3128
  noProxy: .cluster.local,.svc,10.128.0.0/14,127.0.0.1,169.254.169.254,10.196.0.0/16,172.30.0.0/16,.${BASE_DOMAIN},localhost
pullSecret: |
  ${PULL_SECRET}
sshKey: |
  ${SSH_PUB_KEY}
EOF
fi

hosts="# Generated by shiftstack for $CLUSTER_NAME - Do not edit
$FLOATINGIP_API api.${CLUSTER_NAME}.${BASE_DOMAIN}
$FLOATINGIP_INGRESS *.apps.${CLUSTER_NAME}.${BASE_DOMAIN}
$FLOATINGIP_INGRESS console-openshift-console.apps.${CLUSTER_NAME}.${BASE_DOMAIN}
$FLOATINGIP_INGRESS integrated-oauth-server-openshift-authentication.apps.${CLUSTER_NAME}.${BASE_DOMAIN}
$FLOATINGIP_INGRESS oauth-openshift.apps.${CLUSTER_NAME}.${BASE_DOMAIN}
# End of $CLUSTER_NAME nodes"

old_hosts=$(awk "/# Generated by shiftstack for $CLUSTER_NAME - Do not edit/,/# End of $CLUSTER_NAME nodes/" /etc/hosts)

if [ "${hosts}" != "${old_hosts}" ]; then
    echo Updating hosts file
    sudo sed -i "/# Generated by shiftstack for $CLUSTER_NAME - Do not edit/,/# End of $CLUSTER_NAME nodes/d" /etc/hosts
    echo "$hosts" | sudo tee -a /etc/hosts
fi
