#!/bin/bash

set -ex

CLUSTER_NAME="${CLUSTER_NAME:-rhoai}"
BASE_DOMAIN="${BASE_DOMAIN:-shiftstack.test}"
OPENSHIFT_CLIENT="${OPENSHIFT_CLIENT:-$(which oc)}"
OPENSTACK_EXTERNAL_NETWORK="${OPENSTACK_EXTERNAL_NETWORK:-public}"

export KUBECONFIG=../clusters/${CLUSTER_NAME}/auth/kubeconfig
export OS_CLOUD=default

echo "Creating a Floating IP for the worker node that hosts the Openshift Ingress Router Default"

ROUTER_WORKER=$(${OPENSHIFT_CLIENT} get pods -n openshift-ingress -o jsonpath='{.items[0].spec.nodeName}')

ROUTER_FLOATINGIP=$(openstack floating ip create "${OPENSTACK_EXTERNAL_NETWORK}" --description "${CLUSTER_NAME}-router-default" --format value --column floating_ip_address)

openstack server add floating ip "${ROUTER_WORKER}" "${ROUTER_FLOATINGIP}"

hosts="# Generated by rhos-vaf for OpenShift AI $CLUSTER_NAME - Do not edit
$ROUTER_FLOATINGIP rhods-dashboard-redhat-ods-applications.apps.${CLUSTER_NAME}.${BASE_DOMAIN}
# End of rhos-vaf $CLUSTER_NAME endpoints"

old_hosts=$(awk "/# Generated by rhos-vaf for OpenShift AI $CLUSTER_NAME - Do not edit/,/# End of rhos-vaf $CLUSTER_NAME endpoints/" /etc/hosts)

if [ "${hosts}" != "${old_hosts}" ]; then
    echo Updating hosts file
    sudo sed -i "/# Generated by rhos-vaf for OpenShift AI $CLUSTER_NAME - Do not edit/,/# End of rhos-vaf $CLUSTER_NAME endpoints/d" /etc/hosts
    echo "$hosts" | sudo tee -a /etc/hosts
fi
